name: 🚀 Feature request
description: I have a suggestion (and might want to implement myself 🙂)!
labels:
  - "status: triage"
  - "type: feature request"

body:
  - type: textarea
    attributes:
      label: Description
      description: >-
        A clear and concise description of what the feature is...
    validations:
      required: true

  - type: textarea
    attributes:
      label: New or affected resources and data sources
      placeholder: >-
        List of new or impacted resources and data sources...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Potential terraform configuration
      description: >-
        Copy-paste your Terraform configurations here...
      render: HCL
    validations:
      required: true

  - type: textarea
    attributes:
      label: References
      description: >-
        Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation?
