name: 🤔 Question
description: I have a question about the provider (and it's not a bug or a feature request).
labels:
  - "status: triage"
  - "type: question"

body:
  - type: textarea
    attributes:
      label: Question
    validations:
      required: true

  - type: textarea
    attributes:
      label: References
      description: >-
        Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation?
