# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI-6_2:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - run: wget -q -O- https://downloads.opennebula.io/repo/repo.key | sudo apt-key add -
      - run: sudo sh -c 'echo "deb https://downloads.opennebula.io/repo/6.2/Ubuntu/20.04 stable opennebula" > /etc/apt/sources.list.d/opennebula.list'
      - run: sudo apt-get update
      - run: sudo apt-get install opennebula opennebula-flow
      - run: source ${{ github.workspace }}/.ci_scripts/oned.sh
      - run: set -o errexit; source ${{ github.workspace }}/.ci_scripts/terraform.sh
  CI-5_12:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - run: wget -q -O- https://downloads.opennebula.io/repo/repo.key | sudo apt-key add -
      - run: sudo sh -c 'echo "deb https://downloads.opennebula.io/repo/5.12/Ubuntu/20.04 stable opennebula" > /etc/apt/sources.list.d/opennebula.list'
      - run: sudo apt-get update
      - run: sudo apt-get install opennebula opennebula-flow
      - run: source ${{ github.workspace }}/.ci_scripts/oned.sh
      - run: set -o errexit; source ${{ github.workspace }}/.ci_scripts/terraform.sh
